import test from 'node:test';
import assert from 'node:assert/strict';
import {renderWaitlistForm} from './form.mjs';
import {enhanceWaitlist} from './client.mjs';
const entry=process.env.PW_JSDOM_ENTRY;
if(!entry)throw new Error('Use the already installed jsdom entry; no dependency installation');
const {JSDOM}=await import(entry);
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(enabled=true){const dom=new JSDOM(renderWaitlistForm({enabled,privacyPath:'/privacy/'}),{url:'https://site.example.test/'}),form=dom.window.document.querySelector('form');form.querySelector('[name=email]').value='person@example.test';form.querySelector('[name=consent]').checked=true;return {dom,form,email:form.querySelector('[name=email]'),consent:form.querySelector('[name=consent]'),status:form.querySelector('[data-waitlist-status]'),button:form.querySelector('button'),submit(){form.dispatchEvent(new dom.window.Event('submit',{cancelable:true,bubbles:true}));}};}
test('no-JS and unavailable form cannot submit or claim success',()=>{const f=fixture(false);assert.equal(f.button.disabled,true);assert.equal(f.email.disabled,true);assert.equal(f.consent.disabled,true);assert.match(f.status.textContent,/not available yet/);assert.equal(f.form.method,'post');assert.equal(f.form.action,'https://site.example.test/api/cloud-interest');});
test('unavailable client makes zero network requests',async()=>{const f=fixture(false),calls=[];enhanceWaitlist(f.form,{fetchImpl:()=>calls.push('bad')});f.submit();await tick();assert.equal(calls.length,0);});
test('unchecked consent makes zero requests',async()=>{const f=fixture(),calls=[];f.consent.checked=false;enhanceWaitlist(f.form,{fetchImpl:()=>calls.push('bad')});f.submit();await tick();assert.equal(calls.length,0);});
test('unavailable UUID support fails gracefully without a network call',async()=>{const f=fixture(),calls=[];enhanceWaitlist(f.form,{randomUUID:()=>{throw new Error('not supported');},fetchImpl:()=>calls.push('bad')});f.submit();await tick();assert.equal(calls.length,0);assert.match(f.status.textContent,/unavailable in this browser/);assert.equal(f.email.value,'person@example.test');});
test('confirmed200 only clears input after saved response',async()=>{const f=fixture(),calls=[];enhanceWaitlist(f.form,{randomUUID:()=>crypto.randomUUID(),fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json({ok:true,code:'saved'});}});f.submit();await tick();assert.equal(f.email.value,'');assert.equal(f.consent.checked,false);assert.match(f.status.textContent,/request is saved/);assert.equal(calls[0].url,'/api/cloud-interest');assert.equal(calls[0].options.credentials,'same-origin');assert.equal(JSON.parse(calls[0].options.body).consent,true);});
test('HTTP200 without saved readback contract never claims success',async()=>{const f=fixture();enhanceWaitlist(f.form,{fetchImpl:async()=>Response.json({ok:true,code:'pending'})});f.submit();await tick();assert.equal(f.email.value,'person@example.test');assert.doesNotMatch(f.status.textContent,/request is saved/);});
test('failed request preserves input and retry keeps same idempotency key',async()=>{const f=fixture(),keys=[];enhanceWaitlist(f.form,{fetchImpl:async(url,options)=>{keys.push(options.headers['idempotency-key']);return Response.json({ok:false,code:'unavailable'},{status:503});}});f.submit();await tick();assert.equal(f.email.value,'person@example.test');assert.equal(f.consent.checked,true);assert.equal(f.button.disabled,false);f.submit();await tick();assert.equal(keys[0],keys[1]);});
test('changed input after failure uses a new key',async()=>{const f=fixture(),keys=[];enhanceWaitlist(f.form,{fetchImpl:async(url,options)=>{keys.push(options.headers['idempotency-key']);return Response.json({ok:false},{status:503});}});f.submit();await tick();f.email.value='another@example.test';f.submit();await tick();assert.notEqual(keys[0],keys[1]);});
test('pending request locks controls; destruction prevents late success',async()=>{const f=fixture();let resolve;const clean=enhanceWaitlist(f.form,{fetchImpl:()=>new Promise(r=>{resolve=r;})});f.submit();assert.equal(f.button.disabled,true);assert.equal(f.email.disabled,true);assert.equal(f.consent.disabled,true);clean();const before=f.status.textContent;resolve(Response.json({ok:true,code:'saved'}));await tick();assert.equal(f.status.textContent,before);assert.equal(f.email.value,'person@example.test');});
test('rate limit message is retryable and does not clear input',async()=>{const f=fixture();enhanceWaitlist(f.form,{fetchImpl:async()=>Response.json({ok:false,code:'rate_limited'},{status:429})});f.submit();await tick();assert.match(f.status.textContent,/hour/);assert.equal(f.email.value,'person@example.test');});

