import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
import {handleWaitlist,purgeExpired,SQL} from './service.mjs';
import {handleMaintenance,MAINTENANCE_PATH} from './maintenance.mjs';
globalThis.crypto??=webcrypto;
const now=Date.UTC(2026,9,8),origin='https://site.example.test',fixtureKey='synthetic-maintenance-test-only-00000000';
const bundle=readFileSync(new URL('./build-assets/server/index.js',import.meta.url),'utf8');
const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(bundle).toString('base64'));
function database({ghost=false,empty=false}={}){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');sqlite.exec(readFileSync(new URL('./drizzle/0000_cloud_interest.sql',import.meta.url),'utf8'));const calls=[];
 const api={withSession(v){assert.equal(v,'first-primary');calls.push(v);return api;},prepare(sql){assert.equal(sql.split(';').filter(s=>s.trim()).length,1);calls.push(sql);return {bind(...values){return {sql,values,async first(){return sqlite.prepare(sql).get(...values)??null;}};}};},async batch(rows){if(empty)return [];if(ghost)return rows.map(()=>({success:true}));sqlite.exec('BEGIN');try{rows.forEach(r=>sqlite.prepare(r.sql).run(...r.values));sqlite.exec('COMMIT');return rows.map(()=>({success:true}));}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 return {api,sqlite,calls};
}
const env=d=>({DB:d.api,WAITLIST_ORIGIN:origin,WAITLIST_PRODUCTS:'neotoma',WAITLIST_RATE_KEY:'synthetic-rate-test-key-only-00000000',WAITLIST_MAINTENANCE_KEY:fixtureKey});
const maintenance=(headers={},body)=>new Request(origin+MAINTENANCE_PATH,{method:'POST',headers:{authorization:'Bearer '+fixtureKey,...headers},...(body===undefined?{}:{body,duplex:'half'})});
function expired(d){d.sqlite.prepare('INSERT INTO waitlist_signups VALUES(?,?,?,?,?,?,?,?)').run('synthetic-expired','neotoma','synthetic@example.test','cloud-availability','cloud-interest-v1',1,0,1);d.sqlite.prepare('INSERT INTO waitlist_requests VALUES(?,?,?,?)').run('fixture','hash','synthetic-expired',0);d.sqlite.prepare('INSERT INTO waitlist_rate_windows VALUES(?,?,?,?)').run('hash',0,1,1);}
const count=(d,t)=>d.sqlite.prepare(`SELECT count(*) AS n FROM ${t}`).get().n;
test('actual generated migration and journal preserve exact frozen schema and cascade',()=>{const d=database(),journal=JSON.parse(readFileSync(new URL('./drizzle/meta/_journal.json',import.meta.url)));assert.equal(journal.dialect,'sqlite');assert.equal(journal.entries.length,1);assert.equal(journal.entries[0].tag,'0000_cloud_interest');assert.equal(d.sqlite.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='table'").get().n,3);assert.equal(d.sqlite.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='index' AND name NOT LIKE 'sqlite_autoindex%'").get().n,5);assert.equal(d.sqlite.prepare('PRAGMA foreign_key_list(waitlist_requests)').get().on_delete,'CASCADE');assert.throws(()=>d.sqlite.prepare('INSERT INTO waitlist_signups VALUES(?,?,?,?,?,?,?,?)').run('bad','other','synthetic@example.test','cloud-availability','cloud-interest-v1',0,0,1));});
test('bundle is self-contained ESM and preserves identical request ASSETS delegate',async()=>{assert.doesNotMatch(bundle,/^import\s/m);assert.equal(typeof worker.fetch,'function');assert.equal(typeof worker.scheduled,'function');const request=new Request(origin+'/legacy.html');let received;const response=await worker.fetch(request,{ASSETS:{fetch:r=>{received=r;return new Response('legacy surface');}}});assert.equal(received,request);assert.equal(await response.text(),'legacy surface');assert.equal((await worker.fetch(request,{})).status,404);});
test('complete streamed size guard cancels unbounded chunked body before DB',async()=>{const d=database();let cancelled=false,index=0;const body=new ReadableStream({pull(c){if(index++<3)c.enqueue(new Uint8Array(600));else c.close();},cancel(){cancelled=true;}},{highWaterMark:0});const r=new Request(origin+'/api/cloud-interest',{method:'POST',headers:{origin,'content-type':'application/json','idempotency-key':'00000000-0000-4000-8000-000000000001','cf-connecting-ip':'192.0.2.1','content-length':'1'},body,duplex:'half'});assert.equal((await handleWaitlist(r,env(d),{now})).status,413);assert.equal(cancelled,true);assert.equal(d.calls.length,0);});
test('invalid UTF8 never reaches persistence',async()=>{const d=database(),r=new Request(origin+'/api/cloud-interest',{method:'POST',headers:{origin,'content-type':'application/json','idempotency-key':'00000000-0000-4000-8000-000000000001','cf-connecting-ip':'192.0.2.1'},body:new Uint8Array([255])});assert.equal((await handleWaitlist(r,env(d),{now})).status,400);assert.equal(d.calls.length,0);});
test('maintenance is separate server-key protected, not public listing or arbitrary deletion',async()=>{for(const r of [maintenance({authorization:''}),maintenance({authorization:'Bearer '+fixtureKey.replace(/0/g,'1')}),maintenance({origin:'https://foreign.example.test'}),maintenance({},'{"email":"synthetic@example.test","now":9999999999999999}')]){const d=database();expired(d);const response=await handleMaintenance(r,env(d),{now});assert.notEqual(response.status,200);assert.equal(d.calls.length,0);assert.equal(count(d,'waitlist_signups'),1);}assert.equal((await worker.fetch(new Request(origin+MAINTENANCE_PATH),{})).status,405);assert.equal((await handleMaintenance(maintenance(),{}, {now})).status,503);});
test('maintenance deletes expired rows only, cascades receipts, exact count readback before200',async()=>{const d=database();expired(d);d.sqlite.prepare('INSERT INTO waitlist_signups VALUES(?,?,?,?,?,?,?,?)').run('synthetic-current','neotoma','current@example.test','cloud-availability','cloud-interest-v1',1,now,now+180*86400000);const response=await handleMaintenance(maintenance(),env(d),{now});assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,code:'purged'});assert.equal(count(d,'waitlist_signups'),1);assert.equal(count(d,'waitlist_requests'),0);assert.equal(count(d,'waitlist_rate_windows'),0);assert.equal(d.calls.at(-1),SQL.retentionReadback);});
test('retention ghost-success and malformed batch results never claim completion',async()=>{for(const options of [{ghost:true},{empty:true}]){const d=database(options);expired(d);assert.equal((await handleMaintenance(maintenance(),env(d),{now})).status,503);assert.equal(count(d,'waitlist_signups'),1);}});
test('scheduled handler awaits cleanup/failure and does not imply configured trigger',async()=>{const d=database();expired(d);await worker.scheduled({}, {DB:d.api});assert.equal(count(d,'waitlist_signups'),0);const failed=database({ghost:true});expired(failed);await assert.rejects(worker.scheduled({}, {DB:failed.api}),/waitlist_retention_unavailable/);});
test('expired cleanup guards are binding: removed readback mutant falsely reports success',async()=>{const source=readFileSync(new URL('./service.mjs',import.meta.url),'utf8').replace("from './policy.mjs'",`from '${new URL('./policy.mjs',import.meta.url).href}'`),guard="if(!row||['expired_signups','expired_rates','orphan_receipts'].some(k=>!Number.isSafeInteger(row[k])||row[k]!==0))throw new Error('waitlist_retention_unavailable');";assert.ok(source.includes(guard));const mutant=await import('data:text/javascript;base64,'+Buffer.from(source.replace(guard,'/* deliberate RED mutant */')).toString('base64'));const d=database({ghost:true});expired(d);await mutant.purgeExpired({DB:d.api},now);assert.throws(()=>assert.equal(count(d,'waitlist_signups'),0));});
